import Foundation

public class AgenciesProvider
{
   public var agencies: AgenciesListJSON

   public init()
   {
      let decoder = JSONDecoder()
      decoder.keyDecodingStrategy = .convertFromSnakeCase

      let jsonData = json.data( using: .utf8 )!
      agencies = try! decoder.decode( AgenciesListJSON.self, from: jsonData )
   }
}

var json: String =
#"""
{
  "count": 268,
  "next": "https://ll.thespacedevs.com/2.1.0/agencies/?limit=100&offset=100",
  "previous": null,
  "results": [
    {
      "id": 225,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/225/",
      "name": "1worldspace",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "1WSP",
      "description": "A now nonexistent satellite radio network company that operated two satellites to bring coverage with 62 stations to most of the Eastern Hemisphere. They went bankrupt in 2008. There has been a plan to relaunch the company, but it was announced in 2011, and nothing has been done since.",
      "administrator": null,
      "founding_year": "1960",
      "launchers": "None",
      "spacecraft": "AfriStar and AsiaStar",
      "parent": null,
      "image_url": null
    },
    {
      "id": 136,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/136/",
      "name": "Ad Astra Rocket Company",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "AARC",
      "description": "Ad Astra Rocket Company is an American Space Company doing research and development in plasma propulsion technology. This involves using the technology of VASIMR developed in the late '70s, developed by the companies founder, Franklin Diaz. They have begun testing of their VF-200 model engine, built for interplanetary travel.",
      "administrator": "Dr. Franklin Chang Diaz",
      "founding_year": "2005",
      "launchers": "None",
      "spacecraft": "VX-200, VF-200",
      "parent": null,
      "image_url": null
    },
    {
      "id": 133,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/133/",
      "name": "Aerojet",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "Aerojet",
      "description": "An American Propulsion and Rocket manufacturer founded in 1942 that worked on major projects for NASA such as the Apollo CM main engine, the Space Shuttle Orbital Maneuvering System, and engines for the Titan Rockets the launched the likes of Voyager. They merged with Rocketdyne in 2013.",
      "administrator": null,
      "founding_year": "1942",
      "launchers": "Aerobee, Aerojet General X-8",
      "spacecraft": "None",
      "parent": null,
      "image_url": null
    },
    {
      "id": 2,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/2/",
      "name": "Aeronautics and Space Research and Diffusion Center",
      "featured": false,
      "type": "Government",
      "country_code": "URY",
      "abbrev": "CIDA-E",
      "description": "An Uruguayan Government Space and Aeronautics Research Organization founded in 1975. They study and promote aerospace and space issues along with researching into them. They also advise and collaborate with the Uruguayan Air Force.",
      "administrator": null,
      "founding_year": "1975",
      "launchers": "None",
      "spacecraft": "None",
      "parent": null,
      "image_url": null
    },
    {
      "id": 1003,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/1003/",
      "name": "Aérospatiale",
      "featured": false,
      "type": "Government",
      "country_code": "FRA",
      "abbrev": "",
      "description": "Aérospatiale was a French state-owned aerospace manufacturer that built both civilian and military aircraft, rockets and satellites. It was originally known as Société nationale industrielle aérospatiale (SNIAS). Its head office was in the 16th arrondissement of Paris. The name was changed to Aérospatiale during 1970.",
      "administrator": null,
      "founding_year": "1970",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 282,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/282/",
      "name": "Aevum",
      "featured": false,
      "type": null,
      "country_code": "USA",
      "abbrev": "AEV",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 178,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/178/",
      "name": "Airbus Defence and Space",
      "featured": false,
      "type": "Multinational",
      "country_code": "FRA, GER, GBR, ESP, ITA",
      "abbrev": "AIRDS",
      "description": "Airbus Defence and Space is a division of Airbus responsible for defence and aerospace products and services. The division was formed in January 2014 during the corporate restructuring of European Aeronautic Defence and Space (EADS), and comprises the former Airbus Military, Astrium, and Cassidian divisions. It is the world's second largest space company after Boeing and one of the top ten defence companies in the world.",
      "administrator": "Dirk Hoke (CEO)",
      "founding_year": "2014",
      "launchers": "Ariane",
      "spacecraft": "Automated Transfer Vehicle (ATV), Columbus (ISS Science Laboratory), Orion Service Module",
      "parent": null,
      "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/airbus2520defence2520and2520space_image_20190207032423.jpeg"
    },
    {
      "id": 4,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/4/",
      "name": "Algerian Space Agency",
      "featured": false,
      "type": "Government",
      "country_code": "DZA",
      "abbrev": "ASAL",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 156,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/156/",
      "name": "Alliant Techsystems",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "ATK",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 251,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/251/",
      "name": "AlYahSat",
      "featured": false,
      "type": "Commercial",
      "country_code": "ARE",
      "abbrev": "ALYAH",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 134,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/134/",
      "name": "American Rocket Company",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "AMROC",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 125,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/125/",
      "name": "A.M. Makarov Yuzhny Machine-Building Plant",
      "featured": false,
      "type": "Commercial",
      "country_code": "UKR",
      "abbrev": "PA Yuzhmash",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 84,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/84/",
      "name": "Amsat",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA,CAN,DEU,ITA,JPN,IND,GBR",
      "abbrev": "AMSAT",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 131,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/131/",
      "name": "Andrews Space",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "Andrews Space",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 190,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/190/",
      "name": "Antrix Corporation Limited",
      "featured": false,
      "type": "Commercial",
      "country_code": "IND",
      "abbrev": "ACL",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 207,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/207/",
      "name": "Arab Satellite Communications Organization",
      "featured": false,
      "type": "Commercial",
      "country_code": "SAU",
      "abbrev": "ASCO",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 115,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/115/",
      "name": "Arianespace",
      "featured": true,
      "type": "Commercial",
      "country_code": "FRA",
      "abbrev": "ASA",
      "description": "Arianespace SA is a multinational company founded in 1980 as the world's first commercial launch service provider. It undertakes the production, operation, and marketing of the Ariane programme. Their vehicles launch exclusively from French Guiana in South America.",
      "administrator": "CEO: Stéphane Israël",
      "founding_year": "1980",
      "launchers": "Ariane 5 | Vega",
      "spacecraft": "",
      "parent": null,
      "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/arianespace_image_20190207032425.jpeg"
    },
    {
      "id": 139,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/139/",
      "name": "Armadillo Aerospace",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "Armadillo",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 271,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/271/",
      "name": "Army Ballistic Missile Agency",
      "featured": false,
      "type": null,
      "country_code": "USA",
      "abbrev": "ABMA",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 5,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/5/",
      "name": "Asia Pacific Multilateral Cooperation in Space Technology and Applications",
      "featured": false,
      "type": "Multinational",
      "country_code": "CHN,PAK,THA",
      "abbrev": "AP-MCSTA",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 6,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/6/",
      "name": "Asia-Pacific Regional Space Agency Forum",
      "featured": false,
      "type": "Multinational",
      "country_code": "AUS,BGD,BRN,BTN,CAN,KHM,CHN,FRA,DEU,IND,IDN,JPN,LAO,MYS,MNG,MMR,NPL,NZL,PAK,PHL,RUS,SGP,KOR,LKA,THA,USA,VNM",
      "abbrev": "APRSAF",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 7,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/7/",
      "name": "Asia-Pacific Space Cooperation Organization",
      "featured": false,
      "type": "Multinational",
      "country_code": "BGD,CHN,IDN,IRNMNG,PAK,PER,THA,TUR",
      "abbrev": "APSCO",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 285,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/285/",
      "name": "Astra Space",
      "featured": false,
      "type": null,
      "country_code": "USA",
      "abbrev": "AS",
      "description": "Astra Space is a launch vehicle company based in San Francisco, California, that develops pump-fed, liquid bipropellant propulsion engines for DARPA and NASA, currently working towards the first orbital launch of their Astra launch vehicle.",
      "administrator": "Geoffrey Crowley",
      "founding_year": "2005",
      "launchers": "213",
      "spacecraft": "",
      "parent": null,
      "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/astra2520space_image_20200216210038.jpg"
    },
    {
      "id": 81,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/81/",
      "name": "Astrium Satellites",
      "featured": false,
      "type": "Commercial",
      "country_code": "FRA,DEU,ESP,GBR",
      "abbrev": "EADS",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 85,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/85/",
      "name": "Astronautic Technology Sdn Bhd",
      "featured": false,
      "type": "Commercial",
      "country_code": "MYS",
      "abbrev": "ATSB",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 8,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/8/",
      "name": "Austrian Space Agency",
      "featured": false,
      "type": "Government",
      "country_code": "AUT",
      "abbrev": "ALR",
      "description": "The Austrian Space Agency was founded in 1972 and joined the ESA as a member in 1987. In 2005, control of the ALR was transferred to the Austrian Agency for Aerospace. They coordinated the first flight of an Austrian in space with a Soyuz launch in 1990.",
      "administrator": "Andreas Geisler",
      "founding_year": "1972",
      "launchers": "",
      "spacecraft": "Spacelab | GALILEO",
      "parent": null,
      "image_url": null
    },
    {
      "id": 255,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/255/",
      "name": "Avanti Communications",
      "featured": false,
      "type": "Commercial",
      "country_code": "GBR",
      "abbrev": "AVN",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 159,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/159/",
      "name": "Avio S.p.A",
      "featured": false,
      "type": "Commercial",
      "country_code": "ITA",
      "abbrev": "Avio",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 1022,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/1022/",
      "name": "Axiom Space",
      "featured": false,
      "type": "Private",
      "country_code": "USA",
      "abbrev": "AXS",
      "description": "Axiom Space, Inc., also known as Axiom, is an American privately funded aerospace manufacturer and orbital spaceflight services company headquartered in Houston, Texas.",
      "administrator": "Michael Suffredini",
      "founding_year": "2016",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 9,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/9/",
      "name": "Azerbaijan National Aerospace Agency",
      "featured": false,
      "type": "Government",
      "country_code": "AZE",
      "abbrev": "AMAKA",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 86,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/86/",
      "name": "Ball Aerospace & Technologies Corp.",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "BLL",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 1,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/1/",
      "name": "Belarus Space Agency",
      "featured": false,
      "type": "Government",
      "country_code": "BLR",
      "abbrev": "BSA",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 10,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/10/",
      "name": "Belgian Institute for Space Aeronomy",
      "featured": false,
      "type": "Government",
      "country_code": "BEL",
      "abbrev": "BIRA",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 140,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/140/",
      "name": "Bigelow Aerospace",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "Bigelow",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 141,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/141/",
      "name": "Blue Origin",
      "featured": true,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "BO",
      "description": "Blue Origin is an American privately funded aerospace manufacturer and spaceflight services company set up by Amazon.com founder Jeff Bezos with its headquarters in Kent, Washington. The company is developing technologies to enable private human access to space with the goal to dramatically lower costs and increase reliability. Blue Origin currently launches its New Shepard sub-orbital vehicle from its West Texas launch site, they are currently constructing a launch pad for their orbital vehicle New Glenn at Cape Canaveral LC-36.",
      "administrator": "CEO: Jeff Bezos",
      "founding_year": "2000",
      "launchers": "New Shepard | New Glenn",
      "spacecraft": "",
      "parent": null,
      "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/blue2520origin_image_20190207032427.jpeg"
    },
    {
      "id": 80,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/80/",
      "name": "Boeing",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "BA",
      "description": "Boeing as a space agency has recently provided NASA with assistance on sending humans to the ISS from American with both their construction of the CST-100 Starliner crew capsule and their work on the SLS Avionics to return to the moon and beyond. Their ventures in GPS satellite systems and Tracking and Data Relay Satellites provide information about earth-orbiting craft to stations on the ground. They also enable research on the ISS and will be helping with the construction of the Lunar Gateway.",
      "administrator": "Leanne Caret",
      "founding_year": "2002",
      "launchers": "SLS",
      "spacecraft": "Starliner",
      "parent": null,
      "image_url": null
    },
    {
      "id": 11,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/11/",
      "name": "Bolivarian Agency for Space Activities",
      "featured": false,
      "type": "Government",
      "country_code": "VEN",
      "abbrev": "ABAE",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 14,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/14/",
      "name": "Bolivian Space Agency",
      "featured": false,
      "type": "Government",
      "country_code": "BOL",
      "abbrev": "ABAE",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 12,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/12/",
      "name": "Brazilian Space Agency",
      "featured": false,
      "type": "Government",
      "country_code": "BRA",
      "abbrev": "AEB",
      "description": "The Brazilian Space Agency is a space agency in South America.  They work in partnership with the US and Russia aboard the ISS. It was previously operated by the military until 1994. They now operate largely in tandem with other nations. They run a spaceport and rocket launch site both in Brazil. They built the VLM small satellite launch system in tandem with Germany. The VLS-1 was intended to be a primary launch vehicle for the BSA, but it failed 3 times and was canceled. They have restarted work on the system in tandem with the Russian Space Agency.",
      "administrator": "José Raimundo Coelho",
      "founding_year": "1961",
      "launchers": "VLM | VLS",
      "spacecraft": "None",
      "parent": null,
      "image_url": null
    },
    {
      "id": 157,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/157/",
      "name": "Bristol Aerospace Company",
      "featured": false,
      "type": "Commercial",
      "country_code": "CAN",
      "abbrev": "BAC",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 87,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/87/",
      "name": "British Aerospace",
      "featured": false,
      "type": "Commercial",
      "country_code": "GBR",
      "abbrev": "BAE",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 254,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/254/",
      "name": "British Satellite Broadcasting",
      "featured": false,
      "type": "Commercial",
      "country_code": "GBR",
      "abbrev": "BSB",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 230,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/230/",
      "name": "Broadcasting Satellite System Corporation",
      "featured": false,
      "type": "Commercial",
      "country_code": "JPN",
      "abbrev": "BSAT",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 15,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/15/",
      "name": "Bulgarian Space Agency",
      "featured": false,
      "type": "Government",
      "country_code": "BGR",
      "abbrev": "SRI-BAS",
      "description": "The Bulgarian Space Agency has put two Bulgarians onto the ISS in tandem with the Russian Space Agency. Their involvement in space began with the Interkosmos program that helped Communist Bloc countries get access to Soviet space technology. They contributed cosmonauts for a training class, two of which flew aboard the ISS.",
      "administrator": null,
      "founding_year": "1993",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 146,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/146/",
      "name": "Canadian Arrow",
      "featured": false,
      "type": "Commercial",
      "country_code": "CAN",
      "abbrev": "Canadian Arrow",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 16,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/16/",
      "name": "Canadian Space Agency",
      "featured": false,
      "type": "Government",
      "country_code": "CAN",
      "abbrev": "CSA",
      "description": "The Canadian Space Agency was established by the Canadian Space Agency Act which received Royal Assent on May 10, 1990. \r\n\r\nThe Canadian space program is administered by the Canadian Space Agency. Canada has contributed technology, expertise and personnel to the world space effort, especially in collaboration with ESA and NASA. In addition to its astronauts and satellites, some of the most notable Canadian technological contributions to space exploration include the Canadarm on the Space Shuttle and Canadarm2 on the International Space Station.",
      "administrator": null,
      "founding_year": "1990",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 19,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/19/",
      "name": "Centre for Remote Imaging, Sensing and Processing",
      "featured": false,
      "type": "Educational",
      "country_code": "SGP",
      "abbrev": "CRISP",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 189,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/189/",
      "name": "China Aerospace Corporation",
      "featured": false,
      "type": "Government",
      "country_code": "CHN",
      "abbrev": "CASC",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 184,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/184/",
      "name": "China Aerospace Science and Industry Corporation",
      "featured": false,
      "type": "Government",
      "country_code": "CHN",
      "abbrev": "CASIC",
      "description": "The China Aerospace Science & Industry Corporation Limited (CASIC) is a Chinese state-owned corporation that designs, develops and manufactures a range of spacecrafts, launch vehicles, strategic and tactical missile systems, and ground equipment.",
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/china_aerospace_image_20201111143053.png"
    },
    {
      "id": 88,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/88/",
      "name": "China Aerospace Science and Technology Corporation",
      "featured": true,
      "type": "Government",
      "country_code": "CHN",
      "abbrev": "CASC",
      "description": "The China Aerospace Science and Technology Corporation (CASC) is the main contractor for the Chinese space program. It is state-owned and has a number of subordinate entities which design, develop and manufacture a range of spacecraft, launch vehicles, strategic and tactical missile systems, and ground equipment. It was officially established in July 1999 as part of a Chinese government reform drive, having previously been one part of the former China Aerospace Corporation. Various incarnations of the program date back to 1956.",
      "administrator": "Chairmen & President: Lei Fanpei",
      "founding_year": "1999",
      "launchers": "Long March",
      "spacecraft": "",
      "parent": null,
      "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/china2520aerospace2520science2520and2520technology2520corporation_image_20191228094408.jpeg"
    },
    {
      "id": 177,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/177/",
      "name": "China Great Wall Industry Corporation",
      "featured": false,
      "type": "Commercial",
      "country_code": "CHN",
      "abbrev": "CGWIC",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 17,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/17/",
      "name": "China National Space Administration",
      "featured": true,
      "type": "Government",
      "country_code": "CHN",
      "abbrev": "CNSA",
      "description": "The China National Space Administration (CNSA) is the national space agency of the People's Republic of China. It is responsible for the national space program and for planning and development of space activities. CNSA and China Aerospace Corporation (CASC) assumed the authority over space development efforts previously held by the Ministry of Aerospace Industry. The CNSA has many launch sites around China with their orbital sites located in Jiuquan, Xichang, Taiyuan and Wenchang.",
      "administrator": "Administrator: Tang Dengjie",
      "founding_year": "1993",
      "launchers": "",
      "spacecraft": "Shenzhou",
      "parent": null,
      "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/china2520national2520space2520administration_image_20190207032431.jpeg"
    },
    {
      "id": 272,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/272/",
      "name": "Chinarocket Co., Ltd.",
      "featured": false,
      "type": null,
      "country_code": "CHN",
      "abbrev": "CHNR",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 158,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/158/",
      "name": "Chrysler",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "CHR",
      "description": "In July 1959, NASA chose the Redstone missile as the basis for the Mercury-Redstone Launch Vehicle to be used for suborbital test flights of the Project Mercury spacecraft. Three unmanned MRLV launch attempts were made between November 1960 and March 1961, two of which were successful. The MRLV successfully launched the chimpanzee Ham, and astronauts Alan Shepard and Gus Grissom on three suborbital flights in January, May and July 1961, respectively.",
      "administrator": null,
      "founding_year": "1950",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 18,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/18/",
      "name": "Colombian Space Commission",
      "featured": false,
      "type": "Government",
      "country_code": "COL",
      "abbrev": "CCE",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 22,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/22/",
      "name": "Committee on Space Research",
      "featured": false,
      "type": "Multinational",
      "country_code": "ARG,ARM,AUS,AUT,BEL,BGR,BRA,CAN,CHN,TWN,CZE,DNK,EGY,ESP,FIN,FRA,DEU,GRC,HUN,IND,IDN,IRN,ISR,ITA,JPN,MEX,NLD,NGA,NOR,PAK,POL,PRT,ROU,RUS,SVK,ZAF,SWE,CHE,THA,TUR,UKR,GBR,USA",
      "abbrev": "COSPAR",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 20,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/20/",
      "name": "Commonwealth Scientific and Industrial Research Organisation",
      "featured": false,
      "type": "Government",
      "country_code": "AUS",
      "abbrev": "CSIRO",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 21,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/21/",
      "name": "Consultative Committee for Space Data Systems",
      "featured": false,
      "type": "Multinational",
      "country_code": "ITA,GBR,CAN,FRA,CHN,DEU,BRA,JPN,USA,RUS",
      "abbrev": "CCSDS",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 1004,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/1004/",
      "name": "Convair",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "",
      "description": "Convair, previously Consolidated Vultee, was an American aircraft manufacturing company that later expanded into rockets and spacecraft. The company was formed in 1943 by the merger of Consolidated Aircraft and Vultee Aircraft. In 1953 it was purchased by General Dynamics, and operated as their Convair Division for most of its corporate history.",
      "administrator": null,
      "founding_year": "1943",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 142,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/142/",
      "name": "Copenhagen Suborbitals",
      "featured": false,
      "type": "Commercial",
      "country_code": "DNK",
      "abbrev": "CSU",
      "description": "Copenhagen Suborbitals is the world's only manned, amateur, crowd funded space program.  Their stated goal is to have one of the members fly into space (above 100 km), on a sub-orbital spaceflight, in a space capsule on the Spica rocket.As an amateur organisation, the 55 members use their spare time on the project, while at the same time having regular day jobs.",
      "administrator": "Kristian Elof Sørensen",
      "founding_year": "2008",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 23,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/23/",
      "name": "Croatian Space Agency",
      "featured": false,
      "type": "Government",
      "country_code": "HRV",
      "abbrev": "HSA",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 25,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/25/",
      "name": "Danish National Space Center",
      "featured": false,
      "type": "Government",
      "country_code": "DNK",
      "abbrev": "DRC",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 126,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/126/",
      "name": "Deep Space Industries",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "DSI",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 1012,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/1012/",
      "name": "Department of Aerospace Science and Technology",
      "featured": false,
      "type": "Government",
      "country_code": "BRA",
      "abbrev": "",
      "description": "The Brazilian Department of Science and Aerospace Technology is the national military research center for aviation and space flight. It is subordinated to the Brazilian Air Force (FAB). It coordinates all technical and scientific activities related to the aerospace sector in which there are interests by the Ministry of Defence. It was established in 1953. It currently employs several thousand civilian and military personnel.",
      "administrator": null,
      "founding_year": "1953",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 212,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/212/",
      "name": "Digital Globe",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "DGI",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 233,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/233/",
      "name": "Direction générale de l'armement",
      "featured": false,
      "type": "Government",
      "country_code": "FRA",
      "abbrev": "DGA",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 236,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/236/",
      "name": "DirecTV",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "DIREC",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 116,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/116/",
      "name": "EADS Astrium Space Transportation",
      "featured": false,
      "type": "Commercial",
      "country_code": "FRA",
      "abbrev": "EADS",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 249,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/249/",
      "name": "Echostar",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "ECHO",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 1000,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/1000/",
      "name": "Energia",
      "featured": false,
      "type": "Government",
      "country_code": "RUS",
      "abbrev": "OKB-1",
      "description": null,
      "administrator": null,
      "founding_year": "1946",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 117,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/117/",
      "name": "Eurockot Launch Services",
      "featured": false,
      "type": "Commercial",
      "country_code": "FRA, RUS",
      "abbrev": "ELS",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 1015,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/1015/",
      "name": "European Launcher Development Organisation",
      "featured": false,
      "type": "Government",
      "country_code": "EUR",
      "abbrev": "ELDO",
      "description": "The European Launcher Development Organisation (ELDO) is a former European space research organization. It was first developed in order to establish a satellite launch vehicle for Europe. The three-stage rocket developed was named Europa, after the mythical Greek god. Overall, there were 10 launches that occurred under ELDO's funding.",
      "administrator": null,
      "founding_year": "1961",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 232,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/232/",
      "name": "European Organisation for the Exploitation of Meteorological Satellites",
      "featured": false,
      "type": "Multinational",
      "country_code": "AUT,BEL,BGR,HRV,CZE,DNK,EST,FIN,FRA,DEU,GRC,HUN,IRL,ISL,ITA,LVA,LTU,LUX,NLD,NOR,POL,PRT,ROU,SVK,SVN,ESP,SWE,CHE,TUR,GBR",
      "abbrev": "EUMETSAT",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 27,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/27/",
      "name": "European Space Agency",
      "featured": false,
      "type": "Multinational",
      "country_code": "AUT,BEL,CZE,DNK,FIN,FRA,DEU,GRC,IRE,ITA,LUZ,NLD,NOR,POL,PRT,ROU,ESP,SWE,CHE,GBR",
      "abbrev": "ESA",
      "description": "The European Space Agency is an intergovernmental organisation of 22 member states. Established in 1975 and headquartered in Paris, France, ESA has a worldwide staff of about 2,000 employees.\r\n\r\nESA's space flight programme includes human spaceflight (mainly through participation in the International Space Station program); the launch and operation of unmanned exploration missions to other planets and the Moon; Earth observation, science and telecommunication; designing launch vehicles; and maintaining a major spaceport, the Guiana Space Centre at Kourou, French Guiana.",
      "administrator": "Johann-Dietrich Wörner",
      "founding_year": "1975",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 1019,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/1019/",
      "name": "European Space Research Organisation",
      "featured": false,
      "type": "Multinational",
      "country_code": "EUR",
      "abbrev": "ESRO",
      "description": "The European Space Research Organisation (ESRO) was an international organisation founded by 10 European nations with the intention of jointly pursuing scientific research in space. It was founded in 1964. As an organisation ESRO was based on a previously existing international scientific institution, CERN. The ESRO convention, the organisations founding document outlines it as an entity exclusively devoted to scientific pursuits. This was the case for most of its lifetime but in the final years before the formation of ESA, the European Space Agency, ESRO began a programme in the field of telecommunications.",
      "administrator": null,
      "founding_year": "1964",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 229,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/229/",
      "name": "Eutelsat",
      "featured": false,
      "type": "Commercial",
      "country_code": "FRA",
      "abbrev": "EUTEL",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 1001,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/1001/",
      "name": "EXOS Aerospace",
      "featured": false,
      "type": null,
      "country_code": "USA",
      "abbrev": "EXOS",
      "description": "Exos Aerospace Systems & Technologies is an aerospace manufacturer and developer of reusable launch systems intended to support unmanned orbital spaceflight launches, and is based in Caddo Mills, Texas.",
      "administrator": "David Mitchell",
      "founding_year": "2014",
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/exos2520aerospace_image_20190629155318.jpg"
    },
    {
      "id": 194,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/194/",
      "name": "ExPace",
      "featured": false,
      "type": "Commercial",
      "country_code": "CHN",
      "abbrev": "EP",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 89,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/89/",
      "name": "Fairchild Space and Electronics Division",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "FSED",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 60,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/60/",
      "name": "FCT Space Office",
      "featured": false,
      "type": "Government",
      "country_code": "PRT",
      "abbrev": "FTC SO",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 265,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/265/",
      "name": "Firefly Aerospace",
      "featured": false,
      "type": null,
      "country_code": "USA",
      "abbrev": "FA",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 90,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/90/",
      "name": "Fokker Space & Systems",
      "featured": false,
      "type": "Commercial",
      "country_code": "NLD",
      "abbrev": "FSS",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 253,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/253/",
      "name": "French Armed Forces",
      "featured": false,
      "type": "Government",
      "country_code": "FRA",
      "abbrev": "FAF",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 1021,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/1021/",
      "name": "Galactic Energy",
      "featured": false,
      "type": "Commercial",
      "country_code": "CHN",
      "abbrev": "GE",
      "description": "Galactic Energy is a private aerospace company headquartered in Beijing, China. Established by senior engineers in 2018, Galactic Energy engages in low-cost commercial space launch business.",
      "administrator": null,
      "founding_year": "2018",
      "launchers": "Ceres-1, Pallas-1",
      "spacecraft": "",
      "parent": null,
      "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/galactic_energy_image_20201106095228.jpeg"
    },
    {
      "id": 106,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/106/",
      "name": "General Dynamics",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "GD",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 91,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/91/",
      "name": "General Electric",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "GE",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 28,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/28/",
      "name": "Geo-Informatics and Space Technology Development Agency",
      "featured": false,
      "type": "Government",
      "country_code": "THA",
      "abbrev": "GISTDA",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 224,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/224/",
      "name": "GeoOptics",
      "featured": false,
      "type": "Commercial",
      "country_code": "US",
      "abbrev": "GO",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 29,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/29/",
      "name": "German Aerospace Center",
      "featured": false,
      "type": "Government",
      "country_code": "DEU",
      "abbrev": "DLR",
      "description": "The German Aerospace Center is Germany's Center for aerospace, energy, and transportation research. Their main work is as a contributor to the ESA. They have done work both in tandem with the US on Space Shuttle and the ISS, and also with other European Nations on missions like Space Lab and Mars Express.",
      "administrator": "Pascale Ehrenfreund",
      "founding_year": "1969",
      "launchers": "",
      "spacecraft": "Mars Express | Rosetta | Dawn",
      "parent": null,
      "image_url": null
    },
    {
      "id": 188,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/188/",
      "name": "Gilmour Space Technologies",
      "featured": false,
      "type": "Private",
      "country_code": "AUS/SIN",
      "abbrev": "GST",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 187,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/187/",
      "name": "GK Launch Services JV",
      "featured": false,
      "type": "Commercial",
      "country_code": "RUS",
      "abbrev": "GKLSJV",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 204,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/204/",
      "name": "Globalstar",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "GSAT",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 92,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/92/",
      "name": "Hawker Siddeley Dynamics",
      "featured": false,
      "type": "Commercial",
      "country_code": "GBR",
      "abbrev": "HSD",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 238,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/238/",
      "name": "Hisdesat",
      "featured": false,
      "type": "Commercial",
      "country_code": "ESP",
      "abbrev": "HISDE",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 250,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/250/",
      "name": "HispaSat",
      "featured": false,
      "type": "Commercial",
      "country_code": "ESP",
      "abbrev": "HISPA",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 243,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/243/",
      "name": "Hughes",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "HUGH",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 93,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/93/",
      "name": "Hughes Aircraft",
      "featured": false,
      "type": "Commercial",
      "country_code": "USA",
      "abbrev": "HAC",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 30,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/30/",
      "name": "Hungarian Space Office",
      "featured": false,
      "type": "Government",
      "country_code": "HUN",
      "abbrev": "HSO",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 94,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/94/",
      "name": "IHI Corporation",
      "featured": false,
      "type": "Commercial",
      "country_code": "JPN",
      "abbrev": "IHI",
      "description": null,
      "administrator": null,
      "founding_year": null,
      "launchers": "",
      "spacecraft": "",
      "parent": null,
      "image_url": null
    },
    {
      "id": 31,
      "url": "https://ll.thespacedevs.com/2.1.0/agencies/31/",
      "name": "Indian Space Research Organization",
      "featured": true,
      "type": "Government",
      "country_code": "IND",
      "abbrev": "ISRO",
      "description": "The Indian Space Research Organisation (ISRO) is the space agency of the Government of India headquartered in the city of Bangalore. Its vision is to \"harness space technology for national development while pursuing space science research and planetary exploration.\"",
      "administrator": "Director: Kailasavadivoo Sivan",
      "founding_year": "1969",
      "launchers": "PSLV | GSLV",
      "spacecraft": "",
      "parent": null,
      "image_url": "https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/agency_images/indian2520space2520research2520organization_image_20190215225409.jpeg"
    }
  ]
}
"""#
